// Shared diagnostic copy for the WeChat Host and settings client.
export default {
  "微信配置格式错误：{file}。请查看诊断详情，修复后重启 DSH。": "The WeChat configuration is invalid: {file}. See the diagnostic details, fix the file, and restart DSH.",
  "配置文件": "Configuration file",
  "配置字段": "Configuration field",
  "校验原因": "Validation issue",
  "应为 JSON 对象。": "Expected a JSON object.",
  "应为 JSON 数组。": "Expected a JSON array.",
  "配置版本缺失或不受当前插件支持。": "The configuration version is missing or unsupported by this plugin.",
  "字段缺失或不是非空字符串。": "The field is missing or is not a non-empty string.",
  "标识符格式不符合要求。": "The identifier has an invalid format.",
  "标识符与 accountId 派生结果不一致。": "The identifier does not match the value derived from accountId.",
  "账号标识重复。": "The account identifier is duplicated.",
  "微信服务地址不是有效 URL。": "The WeChat service address is not a valid URL.",
  "微信服务地址必须使用受信任的 HTTPS 域名和端口。": "The WeChat service address must use a trusted HTTPS domain and port.",
  "工作区路径必须是当前操作系统的绝对路径。": "The workspace path must be absolute on the current operating system.",
  "Agent Preset 标识无效。": "The Agent Preset identifier is invalid.",
  "模型设置须包含有效的 provider、model 和可选 reasoningEffort。": "Model settings require valid provider and model fields, with an optional valid reasoningEffort.",
  "投递目标的标识、结构或路由不符合当前配置版本要求。": "The delivery target identifier, structure or route is invalid for this configuration version.",
  "当前配置版本不允许此字段。": "This field is not allowed in this configuration version.",
  "JSON 语法无效。": "The JSON syntax is invalid.",
  "请检查微信渠道数据目录中的 {file}，修复后重启 DSH；“重新读取”不会重新加载配置。": "Check {file} in the WeChat channel data directory, fix it, and restart DSH; refreshing the status does not reload configuration.",
  "字段位置中的序号从 0 开始，按文件中的条目顺序计数，不包含真实账号标识。": "Field positions use zero-based entry order in the file without including actual account identifiers.",
  "插件版本": "Plugin version",
  "DSH 微信管理接口返回了无法识别的响应，请重新读取状态。": "The DSH WeChat management endpoint returned an invalid response. Refresh the status.",
  "无法读取现有登录凭据。请检查 DSH 凭据存储。": "Could not read the saved login credential. Check the DSH credential store.",
  "登录凭据无法写入 DSH 凭据存储。请检查凭据存储是否可写。": "Could not save the login credential to DSH. Check whether the credential store is writable.",
  "账号配置无法写入本机。请检查 DSH_HOME 目录权限。": "Could not save the account configuration. Check permissions on DSH_HOME.",
  "无法初始化账号状态或工作区。请检查 DSH_HOME 和工作区目录。": "Could not prepare the account state or workspace. Check DSH_HOME and the workspace directory.",
  "插件无法连接当前 Harness，请检查宿主是否已就绪。": "The plugin could not connect to this Harness. Check whether the host is ready.",
  "Harness 健康检查超时。请确认 dsh web 未阻塞。": "The Harness health check timed out. Check whether the host is responsive.",
  "Harness 健康检查需要身份认证。请检查代理、网关或自定义鉴权配置。": "The Harness health check requires authentication. Check proxy, gateway or custom authentication settings.",
  "本机 Harness 请求被代理要求认证。请让回环地址绕过代理，并检查 NO_PROXY 配置。": "The proxy requires authentication for the local Harness request. Bypass the proxy for loopback addresses and check NO_PROXY.",
  "Harness 异常拒绝了回环地址的健康检查。请检查 HTTP 代理、Harness 源码版本和构建产物。": "Harness rejected a loopback health check. Check the HTTP proxy and the running Harness build.",
  "Harness 的 Host 信任检查拒绝了非回环地址请求。请检查 harnessBaseUrl 与 trustedHosts 配置。": "Harness rejected the non-loopback Host. Check harnessBaseUrl and trustedHosts.",
  "健康检查收到了非 Harness 标准的 403 拒绝响应。请检查代理或网关配置。": "The health check received a non-standard HTTP 403 response. Check proxy or gateway settings.",
  "找不到 Harness 健康检查接口。请确认 Harness 与插件版本兼容。": "The Harness health check endpoint was not found. Check Harness and plugin compatibility.",
  "Harness 健康检查返回服务错误。请查看 DSH 日志。": "The Harness health check returned a service error. Check the DSH logs.",
  "Harness 返回了无法识别的响应。请确认 Harness 与插件版本兼容。": "Harness returned an unrecognized response. Check Harness and plugin compatibility.",
  "Harness 拒绝了健康检查请求。请查看 DSH 日志。": "Harness rejected the health check. Check the DSH logs.",
  "Harness 健康检查发生未知错误。请查看 DSH 日志。": "The Harness health check failed with an unknown error. Check the DSH logs.",
  "消息连接初始化失败。请查看 DSH 日志后重试。": "The message connection could not start. Check the DSH logs and retry.",
  "暂时无法访问微信服务。": "The WeChat service is temporarily unreachable.",
  "微信服务请求超时。": "The WeChat service request timed out.",
  "微信服务请求失败（HTTP {status}）。": "The WeChat service request failed (HTTP {status}).",
  "微信服务返回了无法解析的响应。": "The WeChat service returned an unparseable response.",
  "微信服务没有返回有效二维码。": "The WeChat service did not return a valid QR code.",
  "微信服务返回了不受信任的扫码地址。": "The WeChat service returned an untrusted QR-code URL.",
  "微信服务返回了无效的连接地址。": "The WeChat service returned an invalid connection URL.",
  "微信服务返回了不受信任的连接地址。": "The WeChat service returned an untrusted connection URL.",
  "拒绝访问不受信任的微信服务地址。": "Refusing to access an untrusted WeChat service URL.",
  "微信服务返回了无法识别的扫码状态。": "The WeChat service returned an unrecognized QR-code status.",
  "微信授权成功，但返回的账号凭据不完整。": "WeChat authorized the account but returned incomplete credentials.",
  "微信服务拒绝了二维码申请。": "The WeChat service rejected the QR-code request.",
  "已取得扫码地址，但本机二维码图片生成失败。": "The login URL was obtained, but the QR-code image could not be generated locally.",
  "无法生成微信二维码。": "Could not generate a WeChat QR code.",
  "这次微信绑定任务已不存在，请重新读取状态或生成二维码。": "This WeChat setup attempt no longer exists. Refresh the status or generate a new QR code.",
  "这次微信绑定任务当前不能提交配对码，请重新读取状态。": "This setup attempt is not waiting for a pairing code. Refresh the status.",
  "登录凭据缺失，请移除账号后重新扫码。": "The login credential is missing. Remove the account and scan a new QR code.",
  "微信登录凭据已失效，请移除账号后重新扫码。": "The WeChat login credential has expired. Remove the account and scan a new QR code.",
  "无法从 DSH 凭据存储移除微信登录凭据。": "Could not remove the WeChat login credential from the DSH credential store.",
  "微信账号配置移除失败。": "Could not remove the WeChat account configuration.",
  "无法读取微信账号状态文件。": "Could not read the WeChat account state file.",
  "无法保存微信账号状态文件。": "Could not save the WeChat account state file.",
  "微信账号已移除，但本机状态文件清理失败。": "The WeChat account was removed, but its local state file could not be cleaned up.",
  "无法保存微信工作区设置。": "Could not save the WeChat workspace settings.",
  "微信账号已移除，但工作区设置清理失败。": "The WeChat account was removed, but its workspace settings could not be cleaned up.",
  "微信账号连接启动失败。": "The WeChat account connection could not start.",
  "微信消息同步请求被拒绝。": "WeChat rejected the message sync request.",
  "微信服务未确认停止通知。": "WeChat did not confirm the stop notification.",
  "微信消息连接停止时发生错误。": "An error occurred while stopping the WeChat connection.",
  "无法读取微信连接状态，请重新读取；之前的操作可能已完成。": "Could not read the WeChat connection status. Refresh it; the previous operation may have completed.",
  "微信激活过程中发生未知错误。": "An unknown error occurred while activating the WeChat account.",
  "微信操作发生未知错误。": "The WeChat operation failed with an unknown error.",
  "微信配置格式错误，请检查 config.json 和 workspaces.json 后重启 DSH。": "The WeChat configuration is invalid. Check config.json and workspaces.json, then restart DSH.",
  "微信配置访问权限不足，请检查数据目录权限后重启 DSH。": "The WeChat configuration could not be accessed. Check the data directory permissions and restart DSH.",
  "微信初始化失败，请查看 DSH 启动日志。": "WeChat initialization failed. Check the DSH startup logs.",
  "微信连接未就绪。": "The WeChat connection is not ready.",
  "微信操作失败后，原账号状态恢复失败。": "The previous account state could not be restored after the failed WeChat operation.",
  "原账号状态尚未确认，请重新读取状态，并反馈诊断信息。": "The previous account state has not been confirmed. Refresh the status and share the diagnostic information.",
  "操作未完成，已恢复之前的本机状态。请处理上述问题后重试。": "The operation did not complete. The previous local state was restored. Resolve the problem above before retrying.",
  "凭据由只读来源提供，请在启动 DSH 的配置中检查该来源。": "The credential comes from a read-only source. Check that source in the configuration used to launch DSH.",
  "微信服务域名解析失败，请检查运行 DSH 的机器的网络和 DNS 设置后重试。": "The WeChat service domain could not be resolved. Check the network and DNS settings on the machine running DSH and retry.",
  "请检查 DSH 数据目录和对应文件的读写权限。": "Check read and write permissions on the DSH data directory and the affected file.",
  "磁盘空间不足，请释放空间后重试。": "The disk is full. Free up space and retry.",
  "本机文件格式无效，请检查对应配置或状态文件；不要清空登录凭据。": "The local file format is invalid. Check the affected configuration or state file; do not clear login credentials.",
  "请检查运行 DSH 的机器的系统时间、证书和网络设置。": "Check the system time, certificates and network settings on the machine running DSH.",
  "请移除失效接入并重新扫码绑定。": "Remove the invalid connection and scan a new QR code to connect.",
  "请确认当前 DSH 宿主已就绪，并检查 Harness 与插件实际运行版本及宿主日志。": "Check that this DSH host is ready, and check the running Harness and plugin versions and the host logs.",
  "微信服务限流，请稍后重试。": "The WeChat service is rate-limiting requests. Try again later.",
  "访问被拒绝，请检查服务访问限制；HTTP 状态本身不能确认登录凭据已失效。": "Access was denied. Check service access restrictions; the HTTP status alone does not establish that the login credential expired.",
  "请检查运行 DSH 的机器能否访问微信服务，然后重试。": "Check whether the machine running DSH can access the WeChat service, then retry.",
  "请按参考号查看 DSH 日志，并复制诊断信息反馈。": "Find this reference in the DSH logs and copy the diagnostic information when reporting the issue.",
  "无法完成微信管理请求，请检查 DSH 连接后重新读取状态。": "The WeChat management request could not be completed. Check the DSH connection and refresh the status.",
  "查询微信扫码状态失败": "Could not query WeChat QR-code status",
  "无法完成微信管理请求": "Could not complete the WeChat management request",
  "无法生成微信二维码": "Could not generate a WeChat QR code",
  "状态读取失败，以下是上次读取的状态。": "Status refresh failed. The last known status is shown below.",
  "诊断详情": "Diagnostic details",
  "诊断信息": "Diagnostic information",
  "复制诊断信息": "Copy diagnostic information",
  "诊断信息已复制": "Diagnostic information copied",
  "未取得 Host 诊断参考号。": "No diagnostic reference was received from the host.",
  "无法访问剪贴板，请选择并复制以下诊断信息。": "Clipboard access is unavailable. Select and copy the diagnostic information below.",
  "错误码": "Error code",
  "失败阶段": "Failed step",
  "底层原因": "Underlying cause",
  "HTTP 状态": "HTTP status",
  "微信返回码": "WeChat return code",
  "参考号": "Reference",
  "发生时间": "Time",
  "加载微信配置": "Load WeChat configuration",
  "申请二维码": "Request QR code",
  "生成二维码图片": "Generate QR-code image",
  "查询扫码状态": "Query QR-code status",
  "提交配对码": "Submit pairing code",
  "取消绑定": "Cancel setup",
  "读取登录凭据": "Read login credential",
  "保存登录凭据": "Save login credential",
  "移除登录凭据": "Remove login credential",
  "保存账号配置": "Save account configuration",
  "移除账号配置": "Remove account configuration",
  "读取账号状态": "Read account state",
  "保存账号状态": "Save account state",
  "清理账号状态": "Clean up account state",
  "保存工作区设置": "Save workspace settings",
  "清理工作区设置": "Clean up workspace settings",
  "准备消息连接": "Prepare message connection",
  "激活微信账号": "Activate WeChat account",
  "检查 DSH 宿主": "Check DSH host",
  "启动微信连接": "Start WeChat connection",
  "同步微信消息": "Sync WeChat messages",
  "停止微信连接": "Stop WeChat connection",
  "读取连接状态": "Read connection status",
  "恢复原账号状态": "Restore previous account state",
  "访问 DSH 管理接口": "Access DSH management API"
};
